<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>SoulsProx</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SoulsProx.Tests" />
  </ItemGroup>

</Project>
